### ISSUE TITLE
log会打印 2 次，而且不一样

### ISSUE THREAD

**Issue by Yensan** [ruiyuanlu/CommonScripts#1]
我不知道为什么，用了你的模块，的确是更好了，打印的很美观，但是，总是出现重复打印。这个只出现在屏幕输出，文件没有这种情况。

DEBUG:microchat:last_time = 0, elapsed_time = 1524573448
[DEBUG]   20180424-20:37:28,785 client_tornado.py[line:88]: last_time = 0, elapsed_time = 1524573448

**Comment by Yensan** [comment]
加上一句，self.logger.propagate = False 
就可以解决这个bug

**Comment by ruiyuanlu** [comment]
thx~这是Python自己log模块的问题，之前没有注意到
